#!/bin/bash 
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=32
##SBATCH --cpus-per-task=16
#SBATCH --mem-per-cpu=4000M
##SBATCH --mem=800M
#SBATCH --time=02:00:00
#SBATCH --account=def-rhb
#SBATCH --job-name=bd1w0s1
#SBATCH --output=%x-%j.out
#SBATCH --error=%x-%j.err



#execute as: sbatch run_box_statistics_dm_data_out.sub

root_=/home/cunhad/project/cunhad/cubep3m/simulations/guillimin/
root_out_=/home/cunhad/project/cunhad/cubep3m/simulations/guillimin/box_stat/
spec_=64Mpc_1024c_512p_zi63_wakeGmu2t10m6zi31m
aux_path_=/sample0001/
aux_path_out=
filename_="'15.000xv0.dat'"
lenght_factor_=2
resol_factor_=2
pivot_=[0,0,0]
NSIDE_=64
part_=64
num_cores_=32
data_stream_=1
cutoff_=0.4


root="'$root_'"
root_out="'$root_out_'"
spec="'$spec_'"
aux_path="'$aux_path_'"
aux_path_out="'$aux_path_out_'"
filename="'$filename'"
lenght_factor="$lenght_factor_"
resol_factor="$resol_factor_"
pivot="$pivot_"
NSIDE="'$NSIDE_'"
part="$part_"
num_cores="$num_cores_"
data_stream="$data_stream_"
cutoff="$cutoff_"

#export OMP_NUM_THREADS=$SLURM_CPUS_PER_TASK

module load matlab/2016b

cd ~/project/cunhad/production/NBodyWake/Analysis/wake_detection/box_statistics

matlab -nosplash -nodesktop -r "box_statistics_dm_data_out($root,$root_out,$spec,$aux_path,$aux_path_out,$filename_,$lenght_factor,$resol_factor,$pivot,$NSIDE_,$part,$num_cores,$data_stream,$cutoff);  exit;"
