#!/bin/bash
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=1
##SBATCH --mem-per-cpu=4G
#SBATCH --mem=32G
#SBATCH --time=10:00:00
#SBATCH --account=rrg-rhb
#SBATCH --job-name=mn32ht
#SBATCH --output=%x-%j.out
#SBATCH --error=%x-%j.err
#SBATCH --mail-user=disrael.dacunha@mail.mcgill.ca
#SBATCH --mail-type=END
#SBATCH --mail-type=BEGIN


export OMP_NUM_THREADS=$SLURM_CPUS_PER_TASK
module load matlab/2018a


#(execute as:) bash run_cupep3m_ht
#(or:) sbatch run_cupep3m_ht

spec_nowake_=32Mpc_1024c_512p_zi63_nowakem
spec_wake_=32Mpc_1024c_512p_zi63_wakeGmu1t10m7zi31m
root_=/home/cunhad/project/cunhad/cubep3m/simulations/
root_data_out_=/home/cunhad/project/cunhad/cubep3m/simulations/data/
root_plot_out_=/home/cunhad/project/cunhad/cubep3m/simulations/plot/
root_snan_out_=/home/cunhad/project/cunhad/cubep3m/simulations/snan_gra32/
root_snan_comp_=/home/cunhad/project/cunhad/cubep3m/simulations/snan_gra32_comp/
aux_path_data_out_=
aux_path_plot_out_=
aux_path_snan_out_=
aux_path_snan_comp_=
path_to_original_cubep3m=/home/cunhad/project/cunhad/cubep3m/cubep3m_source/cubep3m_ht
initial_sample_id=2015
final_sample_id=2018

z_insert=31.0
Gmu_insert="1E-7"
checkpoint_wake=2
path_to_matlab_wake_insertion=/home/cunhad/project/cunhad/production/NBodyWake/wake_insertion
path_to_matlab_preprocessing=/home/cunhad/project/cunhad/production/NBodyWake/Analysis/preprocessing/
path_to_matlab_1dproj=/home/cunhad/project/cunhad/production/NBodyWake/Analysis/1dproj/
path_to_matlab_lets=/home/cunhad/project/cunhad/production/NBodyWake/Analysis/wake_detection/lets/
path_to_matlab_snan_comp=/home/cunhad/project/cunhad/production/NBodyWake/Analysis/wake_detection/snan_comparison/

lenght_factor_=1
resol_factor_=2
pivot_=[0,0,0]
rot_angle_=[0,0]
#lim_=minmax
#lim_=[-1" "2]
lim_=minmax
#lim1d_=minmax
#lim1d_=[-1" "2]
lim1d_=minmax
#lim_cwt_=minmax
#lim_cwt_=[-1" "2]
lim_cwt_=minmax
cutoff_=0.2
data_stream_=[1,3]
info_=[0,1,2,3]
analysis_=1
#z_id_range_all
#z_id_range_=[1,3,4,5]
z_id_range_=all

root="'$root_'"
root_data_out="'$root_data_out_'"
root_plot_out="'$root_plot_out_'"
root_snan_out="'$root_snan_out_'"
root_snan_comp="'$root_snan_comp_'"
spec_wake="'$spec_wake_'"
spec_nowake="'$spec_nowake_'"
#aux_path="'$aux_path_'"

aux_path_data_out="'$aux_path_data_out_'"
aux_path_plot_out="'$aux_path_plot_out_'"
aux_path_snan_out="'$aux_path_snan_out_'"
aux_path_snan_comp="'$aux_path_snan_comp_'"
lenght_factor="$lenght_factor_"
resol_factor="$resol_factor_"
pivot="$pivot_"
rot_angle="$rot_angle_"
lim="'$lim_'"
#lim="$lim_"
lim1d="'$lim1d_'"
#lim1d="$lim1d_"
lim_cwt="'$lim_cwt'"
#lim_cwt="$lim_cwt_"
cutoff="$cutoff_"
data_stream="$data_stream_"
info="$info_"
analysis="$analysis_"
z_id_range="'$z_id_range_'"
#z_id_range="$z_id_range_"


#zero pad the sequence

for i in $(seq -f sample"%04g" $initial_sample_id $final_sample_id)
do
	root_spec_sample=$root_$spec_nowake_'/'$i

	#initial simulation

#	mkdir -p $root_spec_sample
#	cp -r $path_to_original_cubep3m $root_spec_sample"/."
#	cd $root_spec_sample"/cubep3m_ht/batch"
#	bash COMPILE_cubep3m.csh
#	bash COMPILE_dist_init.csh
#	srun ./dist_init > out_init.log
#	cd ../source_threads
#	srun ./cubep3m > out.log
	
	#store files data

	cd $path_to_matlab_preprocessing
	aux_path_=$i
	aux_path="'/"$aux_path_"/'"
	matlab -nosplash -nodesktop -r "preprocessing($root,$spec_nowake,$aux_path);  exit;"

	cd $path_to_matlab_1dproj
	matlab -nosplash -nodesktop -r "proj1d_dm_analysis_all($root,$root_data_out,$root_plot_out,$root_snan_out,$spec_nowake,$aux_path,$aux_path_data_out,$aux_path_plot_out,$aux_path_snan_out,$lenght_factor,$resol_factor,$pivot,$rot_angle,$lim,$data_stream,$info,$analysis,$z_id_range);  exit;"

	cd $path_to_matlab_lets
	matlab -nosplash -nodesktop -r "wavelets_1d_dm_analysis_all($root,$root_data_out,$root_plot_out,$root_snan_out,$spec_nowake,$aux_path,$aux_path_data_out,$aux_path_plot_out,$aux_path_snan_out,$lenght_factor,$resol_factor,$pivot,$rot_angle,$lim1d,$lim_cwt,$cutoff,$data_stream,$info,$analysis,$z_id_range);  exit;"

	
	#wake insertion

#	cd $path_to_matlab_wake_insertion
#	matlab -nosplash -nodesktop -r "wake_insertion($root,$spec_nowake,$aux_path,$z_insert,$Gmu_insert);  exit;"

#	rm -rf $root_spec_sample"/cubep3m_ht"


	#run with wake

	root_spec_sample=$root_$spec_wake_'/'$i

#	mkdir -p $root_spec_sample

#	cp -r $path_to_original_cubep3m $root_spec_sample"/."
#	cd $root_spec_sample"/cubep3m_ht/source_threads"
#	sed -i '48s/.*/logical, parameter      :: restart_ic =  .true./' cubepm.par
#	sed -i '49s/.*/integer(4), parameter   :: restart_checkpoint = '"${checkpoint_wake}"' /' cubepm.par	
#	cd ../batch
#	bash COMPILE_cubep3m.csh
#	cd ../source_threads
#	srun ./cubep3m > out.log
#	cd ../../
	
#	rm -rf $root_spec_sample"/cubep3m_ht"

	#store files data

	cd $path_to_matlab_preprocessing
	matlab -nosplash -nodesktop -r "preprocessing($root,$spec_wake,$aux_path);  exit;"
	
	cd $path_to_matlab_1dproj
	matlab -nosplash -nodesktop -r "proj1d_dm_analysis_all($root,$root_data_out,$root_plot_out,$root_snan_out,$spec_wake,$aux_path,$aux_path_data_out,$aux_path_plot_out,$aux_path_snan_out,$lenght_factor,$resol_factor,$pivot,$rot_angle,$lim,$data_stream,$info,$analysis,$z_id_range);  exit;"

        cd $path_to_matlab_lets
       matlab -nosplash -nodesktop -r "wavelets_1d_dm_analysis_all($root,$root_data_out,$root_plot_out,$root_snan_out,$spec_wake,$aux_path,$aux_path_data_out,$aux_path_plot_out,$aux_path_snan_out,$lenght_factor,$resol_factor,$pivot,$rot_angle,$lim1d,$lim_cwt,$cutoff,$data_stream,$info,$analysis,$z_id_range);  exit;"


done

#module load matlab/2017a

cd $path_to_matlab_snan_comp

matlab -nosplash -nodesktop -r "snan_comparison_wavelets_1dproj_withnull($root,$root_snan_out,$root_snan_comp,$aux_path_snan_out,$aux_path_snan_comp,$lenght_factor,$resol_factor,$pivot,$rot_angle,$cutoff,$z_id_range);  exit;"
