#PBS -l nodes=1:ppn=12
#PBS -l walltime=12:00:00
#PBS -A smj-701-aa
#PBS -o outputfile
#PBS -e errorfile
##PBS -N bh1_nwk_sp1_n7

#execute as: qsub -A smj-701-aa run_box_statistics_halos_per_node_test.sub -N bx1_nwk_sp1_0_7 -v ARG1=0,ARG2=7



#execute as: qsub -A smj-701-aa run_box_statistics_halos_per_node_test.sub -N bx1_nwk_sp1_0_7 

root_=/gs/project/smj-701-aa/disrael/cubep3m/simulations/
root_out_=$root_
spec_=64Mpc_1024c_512p_zi63_wakeGmu8t10m7zi31m
aux_path_=/sample0001/
aux_path_out=
NSIDE_=64
#node_i_=0
#node_f_=7
num_cores_=12



root="'$root_'"
root_out="'$root_out_'"
spec="'$spec_'"
aux_path="'$aux_path_'"
aux_path_out="'$aux_path_out_'"
percentage_analysed="'$percentage_analysed_'"
NSIDE="'$NSIDE_'"
#node_i="$node_i_"
#node_f="$node_f_"
num_cores="'$num_cores_'"


export PATH=$PATH:/software/CentOS-6/applications/matlab-2016b/bin

cd ~/production/NBodyWake/Analysis/wake_detection/box_statistics

export OMP_NUM_THREADS=12

for i in {0..7};
do
matlab -nosplash -nodesktop -r "box_statistics_halos_per_node($root,$root_out,$spec,$aux_path,$aux_path_out,$NSIDE_,$i,$num_cores_);  exit;"
done
