#!/bin/bash


#(execute as:) bash run_gadget
#(or:) sbatch run_gadget

export LD_LIBRARY_PATH=/usr/local/lib

box_size_Mpc=32
grid_size=64
particle_size=64
redshift_initial=63
redshift_wake_insertion=31
Gmu_insert="1E-7"
Gmu_digit=1
Gmu_exp=7

NumFilesPerSnapshot=2			#should be smaller than processors
NumFilesWrittenInParallel=2		#%should be smaller than processors
NumProcessors=4

spec_nowake_=$box_size_Mpc'Mpc_'$grid_size'c_'$particle_size'p_zi'$redshift_initial'_nowakem'
spec_wake_=$box_size_Mpc'Mpc_'$grid_size'c_'$particle_size'p_zi'$redshift_initial'_wakeGmu'$Gmu_digit't10m'$Gmu_exp'zi'$redshift_wake_insertion'm'
root_=/home/asus/Dropbox/extras/storage/laptop/simulations_gadget/test/

#root_data_out_=/home/cunhad/project/cunhad/cubep3m/simulations/high/data/
#root_plot_out_=/home/cunhad/project/cunhad/cubep3m/simulations/high/plot/
#root_snan_out_=/home/cunhad/project/cunhad/cubep3m/simulations/high/snan_gra$box_size_Mpc'/'
#root_snan_comp_=/home/cunhad/project/cunhad/cubep3m/simulations/high/snan_gra$box_size_Mpc'_comp/'
#aux_path_data_out_=
#aux_path_plot_out_=
#aux_path_snan_out_=
#aux_path_snan_comp_=
#cubep3m_type=
#cubep3m_type=_high_ht
#cubep3m_type=_ht
#cubep3m_type=_high
#cubep3m_type=_high_ht
path_to_original_gadget=/home/asus/Dropbox/extras/Gadget-2.0.7
path_to_original_2LPT_PNGnonlocal=/home/asus/Dropbox/extras/2LPT_PNGnonlocal


initial_sample_id=0001
final_sample_id=0001

for i in $(seq -f sample"%04g" $initial_sample_id $final_sample_id)
do

	root_spec_sample=$root_$spec_nowake_'/'$i

	#glass initial condition simulation

#        mkdir -p $root_spec_sample
#        cp -r $path_to_original_gadget $root_spec_sample"/."	
#	cd $root_spec_sample"/Gadget-2.0.7/Gadget2"
	
#	cp Makefile_glass Makefile
#	sed -i '22s/.*/OPT   +=  -DPMGRID='"${grid_size}"'/' Makefile
#	sed -i '71s/.*/OPT   +=  -DMAKEGLASS='"$(($particle_size * $particle_size * $particle_size))"'/' Makefile	
#	make
#	mkdir ../../batch
#	mkdir ../../glass
#	cd ../../batch	
#	cp ../Gadget-2.0.7/Gadget2/Gadget2 .
#	cp ../Gadget-2.0.7/Gadget2/parameterfiles/output_list.txt .
#	cp ../Gadget-2.0.7/Gadget2/parameterfiles/glass.param .
#	sed -i '4s#.*#OutputDir          ../glass/ #g' glass.param
#	sed -i '14s#.*#OutputListFilename          ../batch/output_list.txt#g' glass.param
#	sed -i '43s#.*#BoxSize          '"${box_size_Mpc}"'.0#g' glass.param
#	sed -i '53s#.*#NumFilesPerSnapshot          '"${NumFilesPerSnapshot}"'#g' glass.param
#	sed -i '54s#.*#NumFilesWrittenInParallel          '"${NumFilesWrittenInParallel}"'#g' glass.param
#	sed -i '111s#.*#SofteningHalo          '"$(echo 2k $box_size_Mpc 25 /p | dc)"'#g' glass.param
#	sed -i '118s#.*#SofteningHaloMaxPhys  '"$(echo 2k $box_size_Mpc 25 /p | dc)"'  #g' glass.param

#	mpirun -np $NumProcessors ./Gadget2 glass.param

	#Run intial conditions generatior with glass 

	cp -r $path_to_original_2LPT_PNGnonlocal $root_spec_sample"/." 
	cd $root_spec_sample"/2LPT_PNGnonlocal"
	make	
	mkdir ../ic
	cd ../batch
	cp ../2LPT_PNGnonlocal/2LPTnonlocal .
	cp ../2LPT_PNGnonlocal/inputs/2lpt_nonlocal_test.param ic_glass.param
	sed -i '2s#.*#Nmesh         '"${grid_size}"' #g' ic_glass.param
        sed -i '6s#.*#Nsample         '"${grid_size}"' #g' ic_glass.param
        sed -i '15s#.*#Box        '"${box_size_Mpc}"'.0 #g' ic_glass.param
	sed -i '21s#.*#GlassTileFac         '"${grid_size}"' #g' ic_glass.param
	sed -i '30s#.*#Redshift         '"${redshift_initial}"'.0 #g' ic_glass.param
	sed -i '75s#.*#NumFilesWrittenInParallel          '"${NumFilesWrittenInParallel}"'#g' ic_glass.param
	
	mpirun -np $NumProcessors ./2LPTnonlocal ic_glass.param



done
